name: covid19_survey_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  dartz: ^0.9.1
  json_annotation: ^3.0.1
  graphql_flutter: ^3.1.0
  cupertino_icons: ^0.1.3
  flutter_bloc: ^6.0.1
  firebase_auth: ^0.16.1
  get_it: ^4.0.4
  flushbar: ^1.10.4
  injectable: ^1.0.2
  auto_route: ^0.6.6
  grouped_buttons: ^1.0.4
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  lint: ^1.2.0
  artemis: ^5.1.0
  injectable_generator: ^1.0.2
  auto_route_generator: ^0.6.6

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
